apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: flask-app-rollout
  namespace: flask-app
  labels:
    app: flask-app
spec:
  replicas: 4
  strategy:
    canary:
      stableService: flask-app-service
      canaryService: flask-app-canary-service
      steps:
        - setWeight: 25 # Start with 25% traffic to new version
        - pause: {duration: 30s} # Wait 30 seconds
        - setWeight: 50 # Increase to 50% traffic
        - pause: {duration: 30s} # Wait 30 seconds  
        - setWeight: 75 # Increase to 75% traffic
        - pause: {duration: 30s} # Wait 30 seconds
      # Final step: 100% traffic (automatic)
      trafficRouting:
        nginx:
          stableIngress: flask-app-ingress
          additionalIngressAnnotations:
            canary-by-header: "canary"
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: maisara99/jenkins-py:9342e5b
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: ENVIRONMENT
              value: "production"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
